name: Build

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

concurrency:
    group: build-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 45

        steps:
            -   uses: actions/checkout@v5

            -   name: Validate Gradle Wrapper
                uses: gradle/actions/wrapper-validation@v4

            -   name: set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   uses: gradle/actions/setup-gradle@v4
                with:
                    gradle-home-cache-cleanup: true

            -   name: Run tests
                run: ./gradlew test --debug

            -   name: Run check
                run: ./gradlew check

            -   name: Upload test results (HTML)
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: test-results
                    path: '**/build/reports/tests/test/index.html'
